"use client";

import { useState } from "react";
import { Check, ChevronDown, UserRoundCheck, UserRoundX } from "lucide-react";
import type { ManagedCampaignProspect as CampaignProspect } from "@/lib/api";
import { MutationForm } from "../../research/[runId]/report/mutation-form";
import { enrollProspectAction, excludeProspectAction, selectProspectsAction } from "./population-actions";

export function PopulationTable({ workspaceSlug, campaignId, sequenceVersionId, prospects, canMutate }: { workspaceSlug: string; campaignId: string; sequenceVersionId: string; prospects: readonly CampaignProspect[]; canMutate: boolean }) {
  const [selected, setSelected] = useState<string[]>(prospects.filter((item) => item.status === "selected").map((item) => item.contactId));
  const selectAction = selectProspectsAction.bind(null, workspaceSlug, campaignId);
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3 rounded-lg bg-slate-50 p-3"><p className="text-xs text-muted">{prospects.length} prospects scorés · {prospects.filter((item) => item.status === "enrolled").length} enrôlé(s)</p>{canMutate ? <MutationForm action={selectAction} confirmation="Confirmer la sélection de ces prospects ?" successMessage="Prospects sélectionnés."><input name="contactIds" type="hidden" value={selected.join(",")} /><button className="button button-signal" disabled={!selected.length} type="submit"><Check size={14} /> Sélectionner ({selected.length})</button></MutationForm> : <span className="text-xs text-muted">Lecture seule</span>}</div>{prospects.length === 0 ? <div className="rounded-lg border border-dashed border-line px-4 py-8 text-center text-sm text-muted">Aucun prospect dans la population. Les critères ICP, données manquantes et exclusions seront affichés ici.</div> : <div className="overflow-x-auto"><table className="data-table min-w-[760px]"><thead><tr><th>Prospect</th><th>Score explicable</th><th>Statut</th><th>Actions</th></tr></thead><tbody>{prospects.map((prospect) => <ProspectRow campaignId={campaignId} canMutate={canMutate} key={prospect.id} prospect={prospect} selected={selected.includes(prospect.contactId)} sequenceVersionId={sequenceVersionId} setSelected={setSelected} workspaceSlug={workspaceSlug} />)}</tbody></table></div>}</div>;
}

function ProspectRow({ prospect, workspaceSlug, campaignId, sequenceVersionId, canMutate, selected, setSelected }: { prospect: CampaignProspect; workspaceSlug: string; campaignId: string; sequenceVersionId: string; canMutate: boolean; selected: boolean; setSelected: (value: string[] | ((current: string[]) => string[])) => void }) {
  const name = prospect.contact ? `${prospect.contact.firstName} ${prospect.contact.lastName}` : prospect.contactId;
  const enroll = enrollProspectAction.bind(null, workspaceSlug, campaignId, prospect.contactId);
  const exclude = excludeProspectAction.bind(null, workspaceSlug, campaignId, prospect.contactId);
  const excluded = prospect.status === "excluded" || prospect.explanation.exclusions.length > 0;
  return <tr className={excluded ? "bg-red-50/40" : undefined}><td><div className="flex items-start gap-2">{canMutate && prospect.status === "candidate" ? <input aria-label={`Sélectionner ${name}`} checked={selected} onChange={(event) => setSelected((current) => event.target.checked ? [...current, prospect.contactId] : current.filter((id) => id !== prospect.contactId))} type="checkbox" /> : null}<div><strong className="text-sm">{name}</strong><p className="text-[11px] text-muted">{prospect.contact?.employment?.company?.name ?? prospect.contact?.company?.name ?? "Entreprise inconnue"}</p></div></div></td><td><span className={`badge ${excluded ? "badge-danger" : prospect.score >= 70 ? "badge-success" : ""}`}>{Math.round(prospect.score)} / 100</span><Explanation prospect={prospect} /></td><td><span className={`badge ${excluded ? "badge-danger" : prospect.status === "enrolled" ? "badge-success" : ""}`}>{excluded ? "EXCLU · critère exclusif" : prospect.status === "selected" ? "sélectionné" : prospect.status === "enrolled" ? "enrôlé" : "candidat"}</span>{prospect.exclusionReason ? <p className="mt-1 max-w-48 text-[11px] text-danger">{prospect.exclusionReason}</p> : null}</td><td><div className="flex flex-wrap gap-2">{canMutate && prospect.status === "selected" ? <MutationForm action={enroll} confirmation={`Enroller ${name} ? La SequenceVersion ${sequenceVersionId} sera utilisée.`} successMessage="Prospect enrôlé sur la séquence figée."><button className="button button-signal" type="submit"><UserRoundCheck size={13} /> Enroller</button></MutationForm> : null}{canMutate && prospect.status !== "enrolled" && prospect.status !== "excluded" ? <MutationForm action={exclude} className="min-w-40 space-y-2" confirmation={`Exclure ${name} de cette campagne ? La raison sera conservée.`} successMessage="Prospect exclu de la campagne."><input className="control w-full text-xs" name="reason" placeholder="Raison obligatoire" required /><button className="button" type="submit"><UserRoundX size={13} /> Exclure</button></MutationForm> : null}</div></td></tr>;
}

function Explanation({ prospect }: { prospect: CampaignProspect }) {
  return <details className="mt-2 max-w-64 text-[11px]"><summary className="flex cursor-pointer items-center gap-1 text-brand-blue"><ChevronDown size={12} /> Voir l’explication</summary><div className="mt-2 space-y-2 rounded-lg border border-line bg-canvas p-2"><ExplanationGroup label="Faits constatés" items={prospect.explanation.facts} className="text-success" /><ExplanationGroup label="Données manquantes" items={prospect.explanation.missing} className="text-warning" /><ExplanationGroup label="Exclusions" items={prospect.explanation.exclusions} className="text-danger" /></div></details>;
}
function ExplanationGroup({ label, items, className }: { label: string; items: readonly Record<string, unknown>[]; className: string }) { return <div className={className}><strong>{label} ({items.length})</strong>{items.length ? <ul className="mt-1 list-disc pl-4">{items.map((item, index) => <li key={index}>{readable(item)}</li>)}</ul> : <p className="mt-1 text-muted">Aucun</p>}</div>; }
function readable(item: Record<string, unknown>): string { return String(item.message ?? item.reason ?? item.dimension ?? Object.entries(item).map(([key, value]) => `${key}: ${String(value)}`).join(" · ")); }
