import { Activity, AlertTriangle, CheckCircle2, GitBranch, RefreshCcw, ShieldAlert, Webhook } from "lucide-react";
import { notFound } from "next/navigation";
import { consoleJobRecoveryDisposition } from "@outbound/domain/operations/operator-console";
import { getSession, listConsoleDeadLetters, listConsoleJobs, listConsoleRejectedWebhooks, listWorkspaces, traceConsoleCorrelation, type ConsoleJob, type CorrelationTrace } from "@/lib/api";
import { requeueJobAction } from "./actions";

export const metadata = { title: "Console opérateur" };
export const dynamic = "force-dynamic";

type Query = { status?: string | string[]; type?: string; from?: string; to?: string; correlationId?: string; notice?: string; error?: string };

export default async function OperatorConsolePage({ params, searchParams }: { params: Promise<{ workspaceSlug: string }>; searchParams: Promise<Query> }) {
  const [{ workspaceSlug }, query, session, workspaces] = await Promise.all([params, searchParams, getSession(), listWorkspaces()]);
  const workspace = workspaces.find((candidate) => candidate.slug === workspaceSlug);
  if (!session || !workspace || !["owner", "admin", "operator"].includes(workspace.role)) notFound();
  const statuses = (Array.isArray(query.status) ? query.status : query.status ? [query.status] : ["retry", "dead_lettered"]);
  const filters = { ...(query.type ? { type: query.type } : {}), ...(query.from ? { from: query.from } : {}), ...(query.to ? { to: query.to } : {}), limit: 50 };
  const [jobs, deadLetters, rejectedWebhooks] = await Promise.all([
    listConsoleJobs(workspaceSlug, { ...filters, statuses }),
    listConsoleDeadLetters(workspaceSlug, filters),
    listConsoleRejectedWebhooks(workspaceSlug, filters),
  ]);
  let trace: CorrelationTrace | null = null;
  if (query.correlationId?.trim()) trace = await traceConsoleCorrelation(workspaceSlug, query.correlationId.trim());
  const canRequeue = workspace.role === "owner" || workspace.role === "admin";

  return <div className="mx-auto max-w-7xl">
    <header className="flex flex-col gap-4 border-b border-line pb-6 sm:flex-row sm:items-end sm:justify-between"><div><div className="badge badge-signal w-fit"><Activity size={13} /> Exploitation</div><h1 className="page-title mt-3">Console opérateur</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-muted">Diagnostiquez les traitements en échec, suivez une corrélation complète et remettez un job en file sans dupliquer son effet métier.</p></div><span className={deadLetters.length ? "badge badge-warning" : "badge badge-success"}>{deadLetters.length ? `${deadLetters.length} dead letter${deadLetters.length > 1 ? "s" : ""}` : "Tout est sain"}</span></header>
    {query.notice ? <p className="mt-5 rounded-lg border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800" role="status">{query.notice}</p> : null}
    {query.error ? <p className="mt-5 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-danger" role="alert">{errorMessage(query.error)}</p> : null}

    <section className="mt-6 grid gap-3 sm:grid-cols-3"><Metric icon={<AlertTriangle size={18} />} label="Reprises automatiques" value={jobs.filter((job) => consoleJobRecoveryDisposition(job) === "automatic").length} tone="success" /><Metric icon={<ShieldAlert size={18} />} label="Interventions nécessaires" value={jobs.filter((job) => consoleJobRecoveryDisposition(job) === "manual").length} tone={jobs.some((job) => consoleJobRecoveryDisposition(job) === "manual") ? "danger" : "success"} /><Metric icon={<Webhook size={18} />} label="Webhooks rejetés" value={rejectedWebhooks.length} tone={rejectedWebhooks.length ? "warning" : "success"} /></section>

    <section className="panel mt-6"><div className="panel-header"><div><h2 className="font-semibold">Filtres de diagnostic</h2><p className="mt-1 text-xs text-muted">Les résultats restent strictement limités au workspace courant.</p></div></div><form className="grid gap-3 p-4 md:grid-cols-5"><label className="text-xs font-semibold text-muted">État<select className="control mt-1" defaultValue={statuses[0]} name="status"><option value="failed">Tous les échecs</option><option value="retry">Retry planifié</option><option value="dead_lettered">Dead letter</option><option value="running">En cours</option><option value="pending">En attente</option><option value="completed">Terminé</option></select></label><label className="text-xs font-semibold text-muted">Type<input className="control mt-1" defaultValue={query.type ?? ""} name="type" placeholder="campaign.compose" /></label><label className="text-xs font-semibold text-muted">Du<input className="control mt-1" defaultValue={query.from ?? ""} name="from" type="date" /></label><label className="text-xs font-semibold text-muted">Au<input className="control mt-1" defaultValue={query.to ?? ""} name="to" type="date" /></label><div className="flex items-end"><button className="button w-full" type="submit">Filtrer</button></div></form></section>

    <section className="panel mt-6 overflow-hidden"><div className="panel-header"><div><h2 className="font-semibold">Jobs</h2><p className="mt-1 text-xs text-muted">Payloads tronqués et expurgés côté serveur.</p></div><span className="badge">{jobs.length}</span></div>{jobs.length ? <div className="overflow-x-auto"><table className="data-table min-w-[1080px]"><thead><tr><th>Mis à jour</th><th>Type</th><th>État</th><th>Tentatives</th><th>Erreur</th><th>Corrélation</th><th>Diagnostic</th><th className="text-right">Action</th></tr></thead><tbody>{jobs.map((job) => <JobRow canRequeue={canRequeue} job={job} key={job.id} workspaceSlug={workspaceSlug} />)}</tbody></table></div> : <HealthyEmpty />}</section>

    <section className="panel mt-6"><div className="panel-header"><div><h2 className="flex items-center gap-2 font-semibold"><GitBranch size={16} /> Suivre une corrélation</h2><p className="mt-1 text-xs text-muted">Retrouvez la chaîne job → événement outbox → audit.</p></div></div><form className="flex flex-col gap-3 border-b border-line p-4 sm:flex-row"><input className="control flex-1" defaultValue={query.correlationId ?? ""} maxLength={200} name="correlationId" placeholder="campaign:… ou unipile-event:…" required /><button className="button" type="submit">Tracer</button></form>{trace ? <Trace trace={trace} /> : <div className="p-8 text-center text-sm text-muted">Saisissez un identifiant de corrélation pour afficher la chaîne complète.</div>}</section>

    <section className="panel mt-6 overflow-hidden"><div className="panel-header"><div><h2 className="flex items-center gap-2 font-semibold"><Webhook size={16} /> Webhooks rejetés</h2><p className="mt-1 text-xs text-muted">Consultables pour diagnostic, jamais rejouables. Le contenu non authentifié n’est pas conservé, uniquement son hash.</p></div><span className="badge">{rejectedWebhooks.length}</span></div>{rejectedWebhooks.length ? <div className="divide-y divide-line">{rejectedWebhooks.map((webhook) => <div className="grid gap-2 p-4 text-xs sm:grid-cols-[160px_180px_minmax(0,1fr)]" key={webhook.id}><span className="text-muted">{formatDate(webhook.receivedAt)}</span><strong>{webhook.reasonCode ?? "REJECTED"}</strong><span className="break-all text-muted">{webhook.providerEventId}</span></div>)}</div> : <HealthyEmpty />}</section>
  </div>;
}

function JobRow({ job, canRequeue, workspaceSlug }: { job: ConsoleJob; canRequeue: boolean; workspaceSlug: string }) {
  const requeue = requeueJobAction.bind(null, workspaceSlug, job.id);
  const recovery = consoleJobRecoveryDisposition(job);
  return <tr><td className="text-xs text-muted">{formatDate(job.updatedAt)}</td><td><strong className="text-xs">{job.type}</strong><span className="mt-1 block font-mono text-[10px] text-muted">{job.id.slice(0, 8)}</span></td><td><span className={job.status === "dead_lettered" ? "badge badge-danger" : job.status === "retry" ? "badge badge-warning" : "badge"}>{statusLabel(job.status)}</span></td><td className="text-xs">{job.attempts}/{job.maxAttempts}</td><td><strong className="block text-xs text-danger">{job.lastErrorCode ?? "—"}</strong><span className="mt-1 block max-w-56 truncate text-[11px] text-muted">{job.lastErrorMessage ?? ""}</span></td><td><a className="font-mono text-[11px] text-ink underline" href={`?correlationId=${encodeURIComponent(job.correlationId)}`}>{job.correlationId}</a></td><td><details><summary className="cursor-pointer text-xs font-semibold">Voir</summary><pre className="mt-2 max-h-48 max-w-80 overflow-auto rounded bg-navy p-2 text-[10px] text-slate-200">{JSON.stringify(job.payloadPreview, null, 2)}</pre></details></td><td className="text-right">{canRequeue && recovery === "manual" ? <form action={requeue}><button className="button min-h-8 px-2.5 text-xs" type="submit"><RefreshCcw size={13} /> Réparer et relancer</button></form> : <span className="text-xs text-muted">{canRequeue ? recoveryLabel(recovery) : "Lecture seule"}</span>}</td></tr>;
}
function Trace({ trace }: { trace: CorrelationTrace }) { const entries = [...trace.jobs.map((entry) => ({ id: entry.id, at: entry.updatedAt, kind: "Job", label: `${entry.type} · ${statusLabel(entry.status)}` })), ...trace.events.map((entry) => ({ id: entry.id, at: entry.createdAt, kind: "Event", label: entry.eventType })), ...trace.audit.map((entry) => ({ id: entry.id, at: entry.createdAt, kind: "Audit", label: entry.action }))].sort((a,b) => new Date(a.at).getTime() - new Date(b.at).getTime()); return <div className="p-4"><p className="mb-4 break-all font-mono text-xs text-muted">{trace.correlationId}</p>{entries.length ? <ol className="space-y-3">{entries.map((entry) => <li className="flex gap-3" key={`${entry.kind}-${entry.id}`}><span className="mt-1 h-2.5 w-2.5 shrink-0 rounded-full bg-signal" /><div><span className="badge">{entry.kind}</span><strong className="ml-2 text-xs">{entry.label}</strong><p className="mt-1 text-[11px] text-muted">{formatDate(entry.at)}</p></div></li>)}</ol> : <p className="text-sm text-muted">Aucune occurrence dans ce workspace.</p>}</div>; }
function Metric({ icon, label, value, tone }: { icon: React.ReactNode; label: string; value: number; tone: "success" | "warning" | "danger" }) { return <div className="panel flex items-center gap-3 p-4"><span className={`grid h-10 w-10 place-items-center rounded-lg ${tone === "success" ? "bg-emerald-50 text-emerald-700" : tone === "danger" ? "bg-red-50 text-danger" : "bg-amber-50 text-warning"}`}>{icon}</span><div><strong className="block text-xl">{value}</strong><span className="text-xs text-muted">{label}</span></div></div>; }
function HealthyEmpty() { return <div className="flex items-center justify-center gap-2 p-8 text-sm text-muted"><CheckCircle2 className="text-emerald-600" size={17} /> Aucun incident correspondant.</div>; }
function formatDate(value: string) { return new Intl.DateTimeFormat("fr-FR", { dateStyle: "short", timeStyle: "short", timeZone: "Europe/Paris" }).format(new Date(value)); }
function statusLabel(status: string) { return ({ pending: "En attente", running: "En cours", retry: "Retry", completed: "Terminé", dead_lettered: "Dead letter" } as Record<string,string>)[status] ?? status; }
function recoveryLabel(recovery: ReturnType<typeof consoleJobRecoveryDisposition>) { return ({ automatic: "Reprise automatique", blocked: "Bloqué par sécurité", none: "Non relançable", manual: "Intervention requise" } as const)[recovery]; }
function errorMessage(code: string) { return ({ CONSOLE_JOB_ALREADY_QUEUED: "Ce job a déjà été remis en file ou est en cours.", CONSOLE_JOB_COMPLETED: "Un job terminé ne peut pas être relancé.", CONSOLE_JOB_NOT_FOUND: "Ce job n’existe pas dans ce workspace.", CONSOLE_JOB_RETRY_SCHEDULED: "Ce traitement possède déjà une reprise automatique planifiée.", CONSOLE_JOB_MANUAL_RECOVERY_BLOCKED: "La relance manuelle est bloquée car un effet fournisseur ne peut pas être exclu.", CONSOLE_JOB_RECOVERY_STATE_MISMATCH: "L’état métier associé a changé. Rechargez la console avant de réessayer." } as Record<string,string>)[code] ?? "L’action n’a pas pu être appliquée."; }
