CREATE TABLE "social_interaction_sync_states" (
  "id" uuid PRIMARY KEY NOT NULL,
  "workspace_id" uuid NOT NULL REFERENCES "workspaces" ("id") ON DELETE cascade,
  "social_content_id" uuid NOT NULL,
  "connected_account_id" uuid NOT NULL REFERENCES "connected_accounts" ("id") ON DELETE cascade,
  "provider_account_id" varchar(300) NOT NULL,
  "provider_social_id" text NOT NULL,
  "owner_provider_id" text,
  "kind" varchar(40) NOT NULL,
  "scope_key" text NOT NULL,
  "parent_provider_interaction_id" text,
  "cursor" text,
  "scan_token" uuid,
  "status" varchar(40) DEFAULT 'idle' NOT NULL,
  "lease_token" uuid,
  "locked_until" timestamp with time zone,
  "next_sync_at" timestamp with time zone NOT NULL,
  "last_error_code" varchar(160),
  "last_error_message" text,
  "last_attempt_at" timestamp with time zone,
  "last_success_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "social_interaction_sync_states_workspace_content_fk" FOREIGN KEY ("workspace_id", "social_content_id") REFERENCES "social_content_items" ("workspace_id", "id") ON DELETE cascade,
  CONSTRAINT "social_interaction_sync_states_workspace_id_uq" UNIQUE ("workspace_id", "id"),
  CONSTRAINT "social_interaction_sync_states_kind_ck" CHECK ("kind" in ('comments', 'reactions')),
  CONSTRAINT "social_interaction_sync_states_status_ck" CHECK ("status" in ('idle', 'syncing', 'error'))
);

CREATE UNIQUE INDEX "social_interaction_sync_states_scope_uq" ON "social_interaction_sync_states" ("workspace_id", "social_content_id", "kind", "scope_key");

CREATE TABLE "social_interactions" (
  "id" uuid PRIMARY KEY NOT NULL,
  "workspace_id" uuid NOT NULL REFERENCES "workspaces" ("id") ON DELETE cascade,
  "social_content_id" uuid NOT NULL,
  "connected_account_id" uuid NOT NULL REFERENCES "connected_accounts" ("id") ON DELETE cascade,
  "provider_account_id" varchar(300) NOT NULL,
  "network" varchar(40) DEFAULT 'linkedin' NOT NULL,
  "provider" varchar(80) DEFAULT 'unipile' NOT NULL,
  "sync_kind" varchar(40) NOT NULL,
  "scope_key" text NOT NULL,
  "type" varchar(40) NOT NULL,
  "provider_interaction_id" text NOT NULL,
  "parent_provider_interaction_id" text,
  "direction" varchar(40) NOT NULL,
  "actor_provider_id" text,
  "actor_name" text,
  "actor_headline" text,
  "actor_profile_url" text,
  "body" text,
  "reaction" varchar(80),
  "mentioned_provider_id" text,
  "mentioned_name" text,
  "status" varchar(40) DEFAULT 'observed' NOT NULL,
  "occurred_at" timestamp with time zone,
  "first_seen_at" timestamp with time zone NOT NULL,
  "last_seen_at" timestamp with time zone NOT NULL,
  "removed_at" timestamp with time zone,
  "last_scan_token" uuid NOT NULL,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "social_interactions_workspace_content_fk" FOREIGN KEY ("workspace_id", "social_content_id") REFERENCES "social_content_items" ("workspace_id", "id") ON DELETE cascade,
  CONSTRAINT "social_interactions_workspace_id_uq" UNIQUE ("workspace_id", "id"),
  CONSTRAINT "social_interactions_network_ck" CHECK ("network" in ('linkedin')),
  CONSTRAINT "social_interactions_sync_kind_ck" CHECK ("sync_kind" in ('comments', 'reactions')),
  CONSTRAINT "social_interactions_type_ck" CHECK ("type" in ('comment', 'reply', 'reaction', 'mention')),
  CONSTRAINT "social_interactions_direction_ck" CHECK ("direction" in ('owner', 'incoming', 'unknown')),
  CONSTRAINT "social_interactions_status_ck" CHECK ("status" in ('observed', 'removed'))
);

CREATE UNIQUE INDEX "social_interactions_provider_event_uq" ON "social_interactions" ("workspace_id", "social_content_id", "type", "provider_interaction_id");
