CREATE TABLE "attribution_touches" (
  "id" uuid PRIMARY KEY NOT NULL,
  "workspace_id" uuid NOT NULL REFERENCES "workspaces" ("id") ON DELETE cascade,
  "social_content_id" uuid NOT NULL,
  "social_interaction_id" uuid NOT NULL,
  "publication_id" uuid,
  "contact_id" uuid,
  "conversation_id" uuid REFERENCES "conversations" ("id") ON DELETE cascade,
  "campaign_id" uuid,
  "booking_id" uuid,
  "opportunity_id" uuid,
  "kind" varchar(40) NOT NULL,
  "certainty" varchar(40) NOT NULL,
  "rule" varchar(160) NOT NULL,
  "model_version" varchar(80) NOT NULL,
  "confidence" numeric(5, 4) NOT NULL,
  "proof_type" varchar(80) NOT NULL,
  "proof_ref" text,
  "proof_href" text,
  "logical_key" text NOT NULL,
  "status" varchar(40) DEFAULT 'active' NOT NULL,
  "occurred_at" timestamp with time zone NOT NULL,
  "next_resolution_at" timestamp with time zone,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT "attribution_touches_workspace_content_fk" FOREIGN KEY ("workspace_id", "social_content_id") REFERENCES "social_content_items" ("workspace_id", "id") ON DELETE cascade,
  CONSTRAINT "attribution_touches_workspace_interaction_fk" FOREIGN KEY ("workspace_id", "social_interaction_id") REFERENCES "social_interactions" ("workspace_id", "id") ON DELETE cascade,
  CONSTRAINT "attribution_touches_workspace_publication_fk" FOREIGN KEY ("workspace_id", "publication_id") REFERENCES "content_publications" ("workspace_id", "id") ON DELETE cascade,
  CONSTRAINT "attribution_touches_workspace_contact_fk" FOREIGN KEY ("workspace_id", "contact_id") REFERENCES "contacts" ("workspace_id", "id") ON DELETE cascade,
  CONSTRAINT "attribution_touches_workspace_campaign_fk" FOREIGN KEY ("workspace_id", "campaign_id") REFERENCES "campaigns" ("workspace_id", "id") ON DELETE cascade,
  CONSTRAINT "attribution_touches_workspace_booking_fk" FOREIGN KEY ("workspace_id", "booking_id") REFERENCES "calendar_bookings" ("workspace_id", "id") ON DELETE cascade,
  CONSTRAINT "attribution_touches_workspace_opportunity_fk" FOREIGN KEY ("workspace_id", "opportunity_id") REFERENCES "opportunities" ("workspace_id", "id") ON DELETE cascade,
  CONSTRAINT "attribution_touches_workspace_id_uq" UNIQUE ("workspace_id", "id"),
  CONSTRAINT "attribution_touches_kind_ck" CHECK ("kind" in ('identity', 'conversation', 'campaign', 'booking', 'opportunity')),
  CONSTRAINT "attribution_touches_certainty_ck" CHECK ("certainty" in ('evidence', 'inference', 'unknown')),
  CONSTRAINT "attribution_touches_status_ck" CHECK ("status" in ('active', 'superseded')),
  CONSTRAINT "attribution_touches_confidence_ck" CHECK ("confidence" >= 0 and "confidence" <= 1 and ("certainty" <> 'unknown' or "confidence" = 0))
);

CREATE UNIQUE INDEX "attribution_touches_logical_uq" ON "attribution_touches" ("workspace_id", "social_interaction_id", "logical_key");
