import { CalendarClock, ExternalLink, History, RotateCcw, UserX, XCircle } from "lucide-react";
import type { CalendarBooking } from "@/lib/api";
import { MutationForm } from "@/app/w/[workspaceSlug]/research/[runId]/report/mutation-form";
import { cancelCalendarBookingAction, markCalendarBookingNoShowAction, rescheduleCalendarBookingAction } from "@/app/w/[workspaceSlug]/calendar-actions";

export function CalendarBookingsPanel({ bookings, canMutate, workspaceSlug, compact = false }: { bookings: readonly CalendarBooking[]; canMutate: boolean; workspaceSlug: string; compact?: boolean }) {
  return <section className="panel"><div className="panel-header"><div><h2 className="flex items-center gap-2 font-semibold"><CalendarClock size={16} /> Rendez-vous</h2><p className="mt-1 text-xs text-muted">Fuseaux, type et historique restent visibles même après déconnexion de Cal.com.</p></div><span className="badge">{bookings.length}</span></div>{bookings.length ? <div className="divide-y divide-line">{bookings.map((booking) => <BookingCard booking={booking} canMutate={canMutate} compact={compact} key={booking.id} workspaceSlug={workspaceSlug} />)}</div> : <div className="p-8 text-center text-sm text-muted">Aucun rendez-vous. Le Setter peut proposer les premiers créneaux depuis la conversation.</div>}</section>;
}

function BookingCard({ booking, canMutate, workspaceSlug, compact }: { booking: CalendarBooking; canMutate: boolean; workspaceSlug: string; compact: boolean }) {
  const mutable = canMutate && ["requested", "booked"].includes(booking.status);
  const reschedule = rescheduleCalendarBookingAction.bind(null, workspaceSlug, booking.id);
  const cancel = cancelCalendarBookingAction.bind(null, workspaceSlug, booking.id);
  const noShow = markCalendarBookingNoShowAction.bind(null, workspaceSlug, booking.id);
  return <article className="p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className={statusBadge(booking.status)}>{statusLabel(booking.status)}</span>{booking.meetingType ? <span className="badge">{booking.meetingType.title} · {booking.meetingType.lengthMinutes} min</span> : null}</div><p className="mt-2 text-sm font-semibold">{formatDate(booking.startAt, booking.organizerTimeZone)}</p><div className="mt-2 grid gap-1 text-[11px] text-muted"><span>Prospect : {booking.attendeeTimeZone}</span><span>Votre agenda : {booking.organizerTimeZone}</span>{booking.rescheduleCount ? <span>{booking.rescheduleCount} déplacement{booking.rescheduleCount > 1 ? "s" : ""}</span> : null}</div>{booking.meetingUrl ? <a className="mt-2 inline-flex items-center gap-1 text-xs font-semibold text-brand-blue" href={booking.meetingUrl} rel="noreferrer" target="_blank">Rejoindre <ExternalLink size={12} /></a> : null}</div>{booking.cancellationReason ? <p className="max-w-xs text-xs text-muted">Motif : {booking.cancellationReason}</p> : null}</div>
    {mutable ? <div className={`mt-4 grid gap-3 ${compact ? "" : "lg:grid-cols-3"}`}><MutationForm action={reschedule} className="space-y-2 rounded-lg border border-line bg-slate-50 p-3" successMessage="Rendez-vous déplacé."><input name="requestKey" type="hidden" value={`reschedule:${booking.id}:${booking.updatedAt}`} /><p className="flex items-center gap-2 text-xs font-semibold"><RotateCcw size={13} /> Déplacer</p><input className="control w-full" defaultValue={localDateTime(booking.startAt, booking.organizerTimeZone)} name="startLocal" required type="datetime-local" /><select className="control w-full" defaultValue={booking.organizerTimeZone} name="timeZone"><option>Europe/Paris</option><option>Europe/Madrid</option><option>Europe/London</option><option>UTC</option><option>America/New_York</option></select><input className="control w-full" name="reason" placeholder="Motif du déplacement" required /><button className="button w-full" type="submit">Confirmer</button></MutationForm><MutationForm action={noShow} className="space-y-2 rounded-lg border border-warning/30 bg-amber-50 p-3" confirmation="Marquer ce prospect absent ? Les relances courantes resteront arrêtées et une replanification sera proposée." successMessage="No-show enregistré."><input name="requestKey" type="hidden" value={`no-show:${booking.id}:${booking.updatedAt}`} /><p className="flex items-center gap-2 text-xs font-semibold text-warning"><UserX size={13} /> No-show</p><input className="control w-full" defaultValue="Le prospect ne s’est pas présenté" name="reason" required /><button className="button w-full" type="submit">Marquer absent</button></MutationForm><MutationForm action={cancel} className="space-y-2 rounded-lg border border-danger/20 bg-red-50 p-3" confirmation="Annuler ce rendez-vous ? L’historique sera conservé." successMessage="Rendez-vous annulé."><input name="requestKey" type="hidden" value={`cancel:${booking.id}:${booking.updatedAt}`} /><p className="flex items-center gap-2 text-xs font-semibold text-danger"><XCircle size={13} /> Annuler</p><input className="control w-full" name="reason" placeholder="Motif de l’annulation" required /><button className="button w-full text-danger" type="submit">Annuler le RDV</button></MutationForm></div> : null}
    {booking.history.length ? <details className="mt-4"><summary className="flex cursor-pointer items-center gap-2 text-xs font-semibold text-muted"><History size={13} /> Historique ({booking.history.length})</summary><ol className="mt-3 space-y-2 border-l border-line pl-4">{booking.history.map((entry) => <li className="text-[11px] text-muted" key={entry.id}><strong className="text-navy">{statusLabel(entry.action)}</strong> · {formatDate(entry.createdAt, booking.organizerTimeZone)}{entry.reason ? ` — ${entry.reason}` : ""}</li>)}</ol></details> : null}</article>;
}

function statusLabel(status: string) { return ({ requested: "Demandé", booked: "Réservé", rescheduled: "Déplacé", cancelled: "Annulé", no_show: "No-show", completed: "Terminé" } as Record<string,string>)[status] ?? status; }
function statusBadge(status: string) { return status === "booked" || status === "completed" ? "badge badge-success" : status === "no_show" || status === "cancelled" ? "badge badge-warning" : "badge badge-signal"; }
function formatDate(value: string, timeZone: string) { return new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short", timeZone: validTimeZone(timeZone) }).format(new Date(value)); }
function localDateTime(value: string, timeZone: string) { const parts = new Intl.DateTimeFormat("en-CA", { year: "numeric", month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit", hourCycle: "h23", timeZone: validTimeZone(timeZone) }).formatToParts(new Date(value)); const get = (type: Intl.DateTimeFormatPartTypes) => parts.find((part) => part.type === type)?.value ?? "00"; return `${get("year")}-${get("month")}-${get("day")}T${get("hour")}:${get("minute")}`; }
function validTimeZone(value: string) { try { new Intl.DateTimeFormat("fr", { timeZone: value }); return value; } catch { return "Europe/Paris"; } }
